PRN211_Online_Store/PRN211_Online_Store/Models/Feedback.cs
using System;
using System.Collections.Generic;

namespace PRN211_Online_Store.Models
{
    public partial class Feedback
    {
        public Feedback()
        {
            FeedbackAttachments = new HashSet<FeedbackAttachment>();
        }

        public int FeedbackId { get; set; }
        public string Username { get; set; } = null!;
        public int ProductId { get; set; }
        public int? Rating { get; set; }
        public string? Comment { get; set; }
        public DateTime? FeedbackTime { get; set; }

        public virtual Product Product { get; set; } = null!;
        public virtual User UsernameNavigation { get; set; } = null!;
        public virtual ICollection<FeedbackAttachment> FeedbackAttachments { get; set; }
    }
}

PRN211_Online_Store/PRN211_Online_Store/Controllers/FeedbackController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PRN211_Online_Store.Models;
using PRN211_Online_Store.Services;
using System.Net.Mail;

namespace PRN211_Online_Store.Controllers
{
    public class FeedbackController : Controller
    {
        private readonly IWebHostEnvironment _webHostEnvironment;

        public FeedbackController(IWebHostEnvironment webHostEnvironment)
        {
            _webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Feedback(int id, int feedbackId)
        {
            string username = HttpContext.Session.GetString("username");
            if (username == null)
            {
                return RedirectToAction("Login", "Authen");
            }
            Product p = ProductService.FindById(id);
            Feedback f = FeedbackService.FindById(feedbackId);
            ViewBag.FeedbackId = feedbackId;
            var viewModel = (Product: p, Feedback: f);
            return View(viewModel);
        }

        public async Task<IActionResult> CreateFeedbackAsync(int productId, int rating, string comment, IFormFileCollection images)
        {
            // process feedback
            List<FeedbackAttachment> attachments = new List<FeedbackAttachment>();
            foreach (var image in images)
            {
                if (image != null && image.Length > 0)
                {
                    // Generate a unique filename for each image
                    var fileName = $"{Guid.NewGuid().ToString()}{Path.GetExtension(image.FileName)}";
                    var imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "img", fileName);

                    // save the images to wwwroot/img
                    using (var stream = new FileStream(imagePath, FileMode.Create))
                    {
                        await image.CopyToAsync(stream);
                    }
                    FeedbackAttachment att = new FeedbackAttachment();
                    att.FileType = Path.GetExtension(image.FileName);
                    att.FilePath = fileName;
                    attachments.Add(att);
                }
            }
            // save feedback
            Feedback f = new Feedback();
            f.Rating = rating;
            f.Comment = comment;
            f.Username = HttpContext.Session.GetString("username");
            f.ProductId = productId;
            f.FeedbackTime = DateTime.Now;
            f.FeedbackAttachments = attachments;
            if (FeedbackService.AddFeedback(f))
            {
                return RedirectToAction("Details", "Product", new { id = productId });
            }
            else
            {
                return RedirectToAction("Login", "Authen");

            }
        }

        [HttpPost]
        public async Task<IActionResult> EditAsync(int productId, int feedbackId, int rating, string comment, IFormFileCollection images)
        {
            using (PRN211_Online_StoreContext context = new PRN211_Online_StoreContext())
            {
                // get feedback from feedbackId
                var f = context.Feedbacks
                    .Where(f => f.FeedbackId == feedbackId)
                    .Include(f => f.FeedbackAttachments)
                    .Include(f => f.Product)
                    .FirstOrDefault();
                // set feedback as new feedback
                f.Comment = comment;
                f.Rating = rating;
                context.FeedbackAttachments.RemoveRange(f.FeedbackAttachments);
                context.SaveChanges();
                List<FeedbackAttachment> attachments = new List<FeedbackAttachment>();
                // process new images upload
                foreach (var image in images)
                {
                    if (image != null && image.Length > 0)
                    {
                        // Generate a unique filename for each image
                        var fileName = $"{Guid.NewGuid().ToString()}{Path.GetExtension(image.FileName)}";
                        var imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "img", fileName);

                        // save the images to wwwroot/img
                        using (var stream = new FileStream(imagePath, FileMode.Create))
                        {
                            await image.CopyToAsync(stream);
                        }
                        FeedbackAttachment att = new FeedbackAttachment();
                        att.FileType = Path.GetExtension(image.FileName);
                        att.FilePath = fileName;
                        attachments.Add(att);
                    }
                }
                f.FeedbackAttachments = attachments;

                // save changes
                context.SaveChanges();
            }

            // return to product detail page
            //Product p = ProductService.FindById(productId);
            return RedirectToAction("Details", "Product", new { id = productId });

        }

        public IActionResult Delete(int id)
        {
            var f = FeedbackService.FindById(id);
            if (f != null)
            {
                int productId = f.ProductId;
                Product p = ProductService.FindById(productId);
                FeedbackService.DeleteFeedback(id);
                if (p != null)
                {
                    return RedirectToAction("Details", "Product", new { id = productId });
                }
            }
            return RedirectToAction("HomePage", "Home");
        }
    }
}

PRN211_Online_Store/PRN211_Online_Store/Views/Feedback/Feedback.cshtml
@addTagHelper *,Microsoft.AspNetCore.Mvc.TagHelpers
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    int feedbackId = ViewBag.FeedbackId;
}
@using PRN211_Online_Store.Models;
@model (Product Product, Feedback Feedback);
<!DOCTYPE html>
<html>
<head>
    <title>Product Feedback</title>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <link rel="stylesheet" href="~/css/NavBar.css" />
    <link rel="stylesheet" href="~/css/FeedbackPage.css" />
    <link rel="stylesheet" href="~/css/ProductDetail.css" />
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
    </style>
</head>
<body>
    @Html.Partial("_NavBar")
    <hr />
    @Html.Partial("_ProductView", Model.Product)
    <hr />
    <h1>Product Feedback</h1>
    @if (feedbackId != null && feedbackId != 0) // edit feedback
    {
        <form class="feedback-form"
              method="POST"
          asp-controller="Feedback"
          asp-action="Edit"
          asp-route-productId="@Model.Product.ProductId"
          asp-route-feedbackId="@Model.Feedback.FeedbackId"
              enctype="multipart/form-data">
            <p for="rating">Rate the product:</p>
            <div class="star-rating">
                @if (Model.Feedback.Rating == 5)
                {
                    <input id="star-5x" type="radio" name="rating" value="5" checked />
                    <label for="star-5x" title="5 stars">
                        <i class="fa fa-star"></i>
                    </label>
                }
                else
                {
                    <input id="star-5x" type="radio" name="rating" value="5" />
                    <label for="star-5x" title="5 stars">
                        <i class="fa fa-star"></i>
                    </label>
                }

                @if (Model.Feedback.Rating == 4)
                {
                    <input id="star-4x" type="radio" name="rating" value="4" checked />
                    <label for="star-4x" title="4 stars">
                        <i class="fa fa-star"></i>
                    </label>
                }
                else
                {
                    <input id="star-4x" type="radio" name="rating" value="4" />
                    <label for="star-4x" title="4 stars">
                        <i class="fa fa-star"></i>
                    </label>
                }

                @if (Model.Feedback.Rating == 3)
                {
                    <input id="star-3x" type="radio" name="rating" value="3" checked />
                    <label for="star-3x" title="3 stars">
                        <i class="fa fa-star"></i>
                    </label>
                }
                else
                {
                    <input id="star-3x" type="radio" name="rating" value="3" />
                    <label for="star-3x" title="3 stars">
                        <i class="fa fa-star"></i>
                    </label>
                }

                @if (Model.Feedback.Rating == 2)
                {
                    <input id="star-2x" type="radio" name="rating" value="2" checked />
                    <label for="star-2x" title="2 stars">
                        <i class="fa fa-star"></i>
                    </label>
                }
                else
                {
                    <input id="star-2x" type="radio" name="rating" value="2" />
                    <label for="star-2x" title="2 stars">
                        <i class="fa fa-star"></i>
                    </label>
                }

                @if (Model.Feedback.Rating == 1)
                {
                    <input id="star-1x" type="radio" name="rating" value="1" checked />
                    <label for="star-1x" title="1 star">
                        <i class="fa fa-star"></i>
                    </label>
                }
                else
                {
                    <input id="star-1x" type="radio" name="rating" value="1" />
                    <label for="star-1x" title="1 star">
                        <i class="fa fa-star"></i>
                    </label>
                }
            </div>
            <h1>Image Upload</h1>
            <div class="image-upload-form">
                <div class="image-upload-section">
                    <label for="images">Upload Images:</label>
                    <input type="file" name="images" id="images" accept="image/*" multiple>
                </div>

                <div class="image-preview-section">
                    <h3>Image Preview:</h3>
                    <div class="image-preview-container"></div>
                </div>
            </div>
            <div class="comment-section">
                <label for="comment">Leave a comment:</label>
                <textarea name="comment"
                          id="comment"
                          rows="5"
                          placeholder="Enter your comment"
                >@Model.Feedback.Comment</textarea>
            </div>

            <input type="submit" value="Update Feedback"/>
        </form>
    }
    else //create new
    {
        <form class="feedback-form"
              method="POST"
          asp-controller="Feedback"
          asp-action="CreateFeedback"
          asp-route-productId="@Model.Product.ProductId"
              enctype="multipart/form-data">
            <p for="rating">Rate the product:</p>
            <div class="star-rating">
                <input id="star-5x" type="radio" name="rating" value="5" />
                <label for="star-5x" title="5 stars">
                    <i class="fa fa-star"></i>
                </label>

                <input id="star-4x" type="radio" name="rating" value="4" />
                <label for="star-4x" title="4 stars">
                    <i class="fa fa-star"></i>
                </label>

                <input id="star-3x" type="radio" name="rating" value="3" />
                <label for="star-3x" title="3 stars">
                    <i class="fa fa-star"></i>
                </label>

                <input id="star-2x" type="radio" name="rating" value="2" />
                <label for="star-2x" title="2 stars">
                    <i class="fa fa-star"></i>
                </label>

                <input id="star-1x" type="radio" name="rating" value="1" />
                <label for="star-1x" title="1 star">
                    <i class="fa fa-star"></i>
                </label>
            </div>
            <h1>Image Upload</h1>
            <div class="image-upload-form">
                <div class="image-upload-section">
                    <label for="images">Upload Images:</label>
                    <input type="file" name="images" id="images" accept="image/*" multiple>
                </div>

                <div class="image-preview-section">
                    <h3>Image Preview:</h3>
                    <div class="image-preview-container"></div>
                </div>
            </div>
            <div class="comment-section">
                <label for="comment">Leave a comment:</label>
                <textarea name="comment"
                          id="comment"
                          rows="5"
                          placeholder="Enter your comment"></textarea>
            </div>

            <input type="submit" value="Submit Feedback" />
        </form>

    }
    <hr />
</body>
<script>
    /*-----------------------IMAGE PREVIEW-------------------------*/
    const imageUploadInput = document.getElementById('images');
    const imagePreviewContainer = document.querySelector('.image-preview-container');

    imageUploadInput.addEventListener('change', function () {
        imagePreviewContainer.innerHTML = ''; // Clear existing previews

        // Loop through selected files and create previews
        for (let i = 0; i < this.files.length; i++) {
            const file = this.files[i];
            const reader = new FileReader();

            reader.onload = function (event) {
                const imagePreview = document.createElement('img');
                imagePreview.src = event.target.result;
                imagePreviewContainer.appendChild(imagePreview);
            };

            reader.readAsDataURL(file);
        }
    });
</script>
</html>